// Function to get a random question index
function getRandomQuestionIndex() {
  // Check if there are questions left to ask
  if (questions.length === 0) {
    return -1; // No more questions to ask
  }

  // Generate a random index to pick a question
  return Math.floor(Math.random() * questions.length);
}

// Async function to get and return a random question as text
export default async function getPostText() {
  // Get a random index for a question
  const randomIndex = getRandomQuestionIndex();

  // If no more questions left, return null
  if (randomIndex === -1) {
    return '';
  }

  // Get the random question from the questions array
  const randomQuestion = questions[randomIndex];

  // Move the question to the posted array
  posted.push(randomQuestion);

  // Remove the question from the questions array
  questions.splice(randomIndex, 1);

  return randomQuestion;
}


const questions = [
  "Mandi berapa kali sehari?",
  "Makan berapa kali sehari?",
  "Pap foto terakhir di galeri?",
  "Terakhir kali jalan-jalan ke mana?",
  "Kapan terakhir kali ngedate?",
  "Punya pacar atau enggak?",
  "Belakangan lagi sibuk apa?",
  "Makanan kesukaan?",
  "Top 10 anime?",
  "Top 10 movies?",
  "Top 10 songs on your Spotify?",
  "Fav character in Harry Potter?",
  "Current reading?",
  "Apa kegiatan favoritmu di akhir pekan?",
  "Suka nonton film di bioskop atau di rumah?",
  "Bagaimana pengalaman liburan terbaikmu?",
  "Apa hobi kamu?",
  "Minuman favorit?",
  "Kalau bisa pindah ke negara mana pun, kamu pilih ke mana?",
  "Kamu lebih suka musim hujan atau musim panas?",
  "Apa aplikasi yang paling sering kamu pakai?",
  "Apa impian terbesar kamu?",
  "Tempat makan favorit di kota kamu?",
  "Siapa artis favoritmu?",
  "Apa lagu yang lagi sering kamu dengar?",
  "Terakhir kali kamu nonton konser siapa?",
  "Olahraga favoritmu apa?",
  "Kamu suka nonton drama Korea?",
  "Apa film favorit waktu kecil?",
  "Kamu punya hewan peliharaan?",
  "Suka baca buku genre apa?",
  "Pernah coba masak resep baru? Bagaimana hasilnya?",
  "Kalau bisa punya kekuatan super, kamu mau apa?",
  "Apa pekerjaan impianmu?",
  "Siapa tokoh inspiratif buat kamu?",
  "Kapan terakhir kali kamu ketawa sampai sakit perut?",
  "Apa yang membuat kamu bahagia?",
  "Apa hal terkonyol yang pernah kamu lakukan?",
  "Apa tujuan liburan impian kamu?",
  "Suka makanan pedas?",
  "Apa restoran favoritmu?",
  "Siapa teman terbaikmu?",
  "Kamu suka nonton serial TV? Apa favoritmu?",
  "Apa game favoritmu?",
  "Kapan terakhir kali kamu menulis surat tangan?",
  "Bagaimana caramu melepas stres?",
  "Apa kenangan masa kecil yang paling berkesan?",
  "Kamu lebih suka pantai atau gunung?",
  "Apa skill yang ingin kamu pelajari?",
  "Suka tanaman? Apa tanaman favoritmu?",
  "Pernah ikut lomba apa saja?",
  "Apa pencapaian terbesar dalam hidupmu?",
  "Kamu lebih suka teh atau kopi?",
  "Siapa yang paling sering kamu ajak ngobrol?",
  "Apa hal paling menantang yang pernah kamu lakukan?",
  "Apa yang paling kamu sukai dari diri sendiri?",
  "Pernah ke luar negeri? Ke mana saja?",
  "Apa makanan yang paling aneh yang pernah kamu coba?",
  "Kamu suka pergi ke museum?",
  "Apa warna favoritmu?",
  "Siapa karakter favoritmu di film atau TV?",
  "Kamu lebih suka pagi atau malam hari?",
  "Apa tempat paling menarik yang pernah kamu kunjungi?",
  "Apa yang selalu ada di tasmu?",
  "Kamu punya saudara berapa?",
  "Suka berbelanja online atau langsung ke toko?",
  "Apa parfum favoritmu?",
  "Bagaimana caramu merayakan ulang tahun?",
  "Apa pekerjaan rumah yang paling kamu benci?",
  "Kamu suka mendengarkan podcast? Apa favoritmu?",
  "Apa yang paling kamu takuti?",
  "Apa yang kamu lakukan saat hari libur?",
  "Suka pergi ke pesta?",
  "Kamu lebih suka sendirian atau ramai-ramai?",
  "Apa yang membuat kamu semangat?",
  "Apa yang paling kamu banggakan dari dirimu?",
  "Suka mengoleksi barang tertentu?",
  "Apa acara TV yang paling kamu tunggu-tunggu?",
  "Kamu suka pergi ke taman bermain?",
  "Apa yang kamu lakukan saat hujan?",
  "Kamu lebih suka es krim atau kue?",
  "Apa hal pertama yang kamu lakukan setelah bangun tidur?",
  "Apa hal terakhir yang kamu lakukan sebelum tidur?",
  "Suka mencoba makanan baru?",
  "Apa film terakhir yang kamu tonton di bioskop?",
  "Apa yang membuat kamu merasa tenang?",
  "Kamu suka berfoto?",
  "Apa kenangan indah yang tidak akan kamu lupakan?",
  "Suka bersepeda?",
  "Apa yang ingin kamu lakukan 5 tahun ke depan?",
  "Bagaimana hubunganmu dengan keluarga?",
  "Apa acara favorit saat kamu masih kecil?",
  "Suka main game di HP?",
  "Apa hadiah terbaik yang pernah kamu terima?",
  "Kamu suka olahraga air?",
  "Apa yang membuat kamu tertarik untuk belajar sesuatu yang baru?",
  "Kamu suka karaoke?",
  "Apa yang paling kamu rindukan dari masa kecil?",
  "Apa yang membuat kamu marah?",
  "Bagaimana cara kamu mengatasi rasa bosan?",
  "Suka nonton film horor?",
  "Apa proyek DIY yang pernah kamu coba?",
  "Apa yang membuat kamu termotivasi?",
  "Suka mendengarkan musik klasik?",
  "Apa tradisi keluarga yang paling kamu sukai?",
  "Kamu lebih suka matahari terbit atau matahari terbenam?",
  "Apa yang ingin kamu capai dalam hidup?",
  "Suka mengikuti tren fashion?",
  "Apa yang membuat kamu tertarik pada seseorang?",
  "Apa kenangan liburan yang paling menyenangkan?",
  "Kamu suka mencoba olahraga ekstrem?",
  "Apa makanan yang paling sering kamu masak di rumah?",
  "Apa yang kamu lakukan saat merasa sedih?",
  "Kamu lebih suka tinggal di kota atau desa?",
  "Apa pencapaian yang paling membanggakan bagi kamu?",
  "Suka menonton acara masak-memasak?",
  "Apa hal pertama yang kamu pikirkan saat bangun tidur?",
  "Bagaimana cara kamu menjaga kesehatan?",
  "Apa yang kamu lakukan saat merasa stres?",
  "Apa restoran cepat saji favoritmu?",
  "Suka pergi ke perpustakaan?",
  "Apa kenangan terbaik dengan teman-temanmu?",
  "Kamu suka menulis?",
  "Apa yang ingin kamu pelajari di masa depan?",
  "Apa hal yang paling menyenangkan dari pekerjaanmu?",
  "Kamu suka memakai aksesoris?",
  "Apa film kartun favoritmu?",
  "Apa yang membuat kamu merasa bersemangat?",
  "Suka mengikuti kompetisi?",
  "Apa yang paling kamu sukai dari tempat tinggalmu?",
  "Suka pergi ke pantai?",
  "Apa yang membuat kamu merasa bangga?",
  "Apa yang ingin kamu capai tahun ini?",
  "Kamu suka belajar bahasa baru?",
  "Apa yang membuat kamu tertawa?",
  "Suka menonton video lucu di internet?",
  "Apa tempat paling romantis yang pernah kamu kunjungi?",
  "Apa kegiatan favoritmu di malam hari?",
  "Apa yang paling kamu nikmati dari akhir pekan?",
  "Kamu suka mencoba resep baru?",
  "Apa hal yang paling kamu rindukan dari masa sekolah?",
  "Apa yang membuat kamu merasa puas?",
  "Suka pergi ke kebun binatang?",
  "Apa yang ingin kamu lakukan setelah pensiun?",
  "Apa yang kamu lakukan saat libur panjang?",
  "Suka membaca majalah?",
  "Apa kenangan terbaik dengan keluargamu?",
  "Apa yang membuat kamu merasa nyaman?",
  "Suka pergi ke konser musik?",
  "Apa film yang paling sering kamu tonton?",
  "Apa yang membuat kamu tertarik pada sebuah buku?",
  "Kamu suka main puzzle?",
  "Apa lagu yang selalu membuat kamu semangat?",
  "Apa yang paling kamu sukai dari musim gugur?",
  "Suka pergi ke taman hiburan?",
  "Apa film animasi favoritmu?",
  "Apa yang membuat kamu merasa aman?",
  "Suka mencoba makeup baru?",
  "Apa acara televisi favorit saat ini?",
  "Apa hal paling romantis yang pernah kamu lakukan?",
  "Suka bermain kartu?",
  "Apa kenangan liburan yang paling lucu?",
  "Apa yang membuat kamu merasa tenang?",
  "Suka mencoba makanan dari berbagai negara?",
  "Apa yang membuat kamu tertarik pada sebuah film?",
  "Suka pergi ke acara festival?",
  "Apa kenangan favorit dengan sahabatmu?",
  "Apa yang paling kamu sukai dari musim dingin?",
  "Suka memelihara tanaman di rumah?",
  "Apa yang membuat kamu merasa spesial?",
  "Apa yang paling kamu sukai dari dirimu?",
  "Suka bermain alat musik?",
  "Apa kenangan terindah dengan keluarga?",
  "Apa yang membuat kamu merasa bebas?",
  "Suka berkemah?",
  "Apa yang paling kamu sukai dari pekerjaanmu?",
  "Apa kenangan terbaik dengan pasanganmu?",
  "Apa yang membuat kamu merasa bangga dengan diri sendiri?",
  "Suka pergi ke pantai di malam hari?",
  "Apa yang membuat kamu merasa nyaman di rumah?",
  "Suka mencoba hobi baru?",
  "Apa yang paling kamu sukai dari budaya lain?",
  "Apa kenangan favorit dengan teman-temanmu?",
  "Apa yang membuat kamu merasa kuat?",
  "Suka menghadiri acara seni?",
  "Apa yang paling kamu sukai dari makanan?",
  "Apa kenangan liburan yang paling berkesan?",
  "Apa yang membuat kamu merasa bersyukur?",
  "Suka berkunjung ke museum seni?",
  "Apa yang paling kamu sukai dari kota tempat tinggalmu?",
  "Apa kenangan favorit saat sekolah?",
  "Apa yang membuat kamu merasa optimis?",
  "Suka mengikuti acara kuliner?",
  "Apa yang paling kamu sukai dari alam?",
  "Apa kenangan terbaik dengan hewan peliharaanmu?",
  "Apa yang membuat kamu merasa puas dengan hidup?",
  "Suka pergi ke acara olahraga?",
  "Apa yang paling kamu sukai dari kegiatan outdoor?",
  "Apa kenangan liburan yang paling menyenangkan?",
  "Apa yang membuat kamu merasa bahagia setiap hari?",
  "Suka mencoba hobi baru?",
  "Apa yang paling kamu sukai dari musim semi?",
  "Apa kenangan liburan yang paling mengesankan?",
  "Apa yang membuat kamu merasa sejahtera?",
  "Suka pergi ke acara musik?",
  "Apa yang paling kamu sukai dari seni?",
  "Apa kenangan terbaik dengan pasanganmu?",
  "Apa yang membuat kamu merasa penuh energi?",
  "Suka pergi ke taman kota?",
  "Apa yang paling kamu sukai dari teknologi?",
  "Apa kenangan liburan yang paling menyentuh hati?",
  "Apa yang membuat kamu merasa damai?",
  "Suka mengikuti trend fashion?",
  "Apa yang paling kamu sukai dari sains?"
];

// eslint-disable-next-line sonarjs/no-unused-collection
const posted = []