name: "Post to Bluesky"

on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:  # Allows manual triggering

jobs:
  fetchSheetData:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'getSheetData'  # Trigger manually or by custom event
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - run: npm ci
      - run: npm run build
      - run: npm start
      
      - name: Fetch Sheet Data
        run: node dist/getSheetQuestion.js
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

  runPostTask:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' && github.event.schedule == '0 */2 * * *' || github.event_name == 'workflow_dispatch'  # Run every 2 hours or manually
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - run: npm ci
      - run: npm run build
      - run: npm start
      
      - name: Run Post Task
        run: node dist/getRandomQuestion.js
        env:
          BSKY_HANDLE: ${{ secrets.BSKY_HANDLE }}
          BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
